//Bags
export const WOMEN_REQUEST = 'WOMEN_REQUEST'
export const WOMEN_SUCCESS = 'WOMEN_SUCCESS'
export const WOMEN_FAIL = 'WOMEN_FAIL'

export const TOTE_REQUEST = 'TOTE_REQUEST'
export const TOTE_SUCCESS = 'TOTE_SUCCESS'
export const TOTE_FAIL = 'TOTE_FAIL'

export const OFFICE_REQUEST = 'OFFICE_REQUEST'
export const OFFICE_SUCCESS = 'OFFICE_SUCCESS'
export const OFFICE_FAIL = 'OFFICE_FAIL'

export const TRAVEL_REQUEST = 'TRAVEL_REQUEST'
export const TRAVEL_SUCCESS = 'TRAVEL_SUCCESS'
export const TRAVEL_FAIL = 'TRAVEL_FAIL'

//Home
export const TABLEWARE_REQUEST = 'TABLEWARE_REQEUST'
export const TABLEWARE_SUCCESS = 'TABLEWARE_SUCCESS'
export const TABLEWARE_FAIL = 'TABLEWARE_FAIL'

export const KITCHEN_REQUEST = 'KITCHEN_REQUEST'
export const KITCHEN_SUCCESS = 'KITCHEN_SUCCESS'
export const KITCHEN_FAIL = 'KITCHEN_FAIL'

export const LAUNDRY_REQUEST = 'LAUNDRY_REQUEST'
export const LAUNDRY_SUCCESS = 'LAUNDRY_SUCCESS'
export const LAUNDRY_FAIL = 'LAUNDRY_FAIL'

export const GARDEN_REQUEST = 'GARDEN_REQUEST'
export const GARDEN_SUCCESS = 'GARDEN_SUCCESS'
export const GARDEN_FAIL = 'GARDEN_FAIL'

//Lifestyle
export const HYGIENE_REQUEST = 'HYGIENE_REQUEST'
export const HYGIENE_SUCCESS = 'HYGIENE_SUCCESS'
export const HYGIENE_FAIL = 'HYGIENE_FAIL'

export const WORKOUT_REQUEST = 'WORKOUT_REQUEST'
export const WORKOUT_SUCCESS = 'WORKOUT_SUCCESS'
export const WORKOUT_FAIL = 'WORKOUT_FAIL'

export const STATIONARY_REQUEST = 'STATIONARY_REQUEST'
export const STATIONARY_SUCCESS = 'STATIONARY_SUCCESS'
export const STATIONARY_FAIL = 'STATIONARY_FAIL'

//Gift
export const GIFT_BOX_REQUEST = 'GIFT_BOX_REQUEST'
export const GIFT_BOX_SUCCESS = 'GIFT_BAG_SUCCESS'
export const GIFT_BOX_FAIL = 'GIFT_BOX_FAIL'

export const GIFT_BAG_REQUEST = 'GIFT_BAG_REQUEST'
export const GIFT_BAG_SUCCESS = 'GIFT_BAG_SUCCESS'
export const GIFT_BAG_FAIL = 'GIFT_BAG_FAIL'

export const ACCESSORIES_REQUEST = 'ACCESSORIES_REQUEST'
export const ACCESSORIES_SUCCESS = 'ACCESSORIES_SUCCESS'
export const ACCESSORIES_FAIL = 'ACCESSORIES_FAIL'

//Storage
export const ORGANISERS_REQUEST = 'ORGANISERS_REQUEST'
export const ORGANISERS_SUCCESS = 'ORGANISERS_SUCCESS'
export const ORGANISERS_FAIL = 'ORGANISERS_FAIL'

export const HOME_REQUEST = 'HOME_REQUEST'
export const HOME_SUCCESS = 'HOME_SUCCESS'
export const HOME_FAIL = 'HOME_FAIL'

//Accessories
export const ON_THE_GO_REQUEST = 'ON_THE_GO_REQUEST'
export const ON_THE_GO_SUCCESS = 'ON_THE_GO_SUCCESS'
export const ON_THE_GO_FAIL = 'ON_THE_GO_FAIL'

export const WALLET_REQUEST = 'WALLET_REQUEST'
export const WALLET_SUCCESS = 'WALLET_SUCCESS'
export const WALLET_FAIL = 'WALLET_FAIL'