export const HOME_SCREEN_BAGS_REQUEST = 'HOME_SCREEN_BAGS_REQUEST'
export const HOME_SCREEN_BAGS_SUCCESS = 'HOME_SCREEN_BAGS_SUCCESS'
export const HOME_SCREEN_BAGS_FAIL = 'HOME_SCREEN_BAGS_FAIL'

export const HOME_SCREEN_HOME_REQUEST = 'HOME_SCREEN_HOME_REQUEST'
export const HOME_SCREEN_HOME_SUCCESS = 'HOME_SCREEN_HOME_SUCCESS'
export const HOME_SCREEN_HOME_FAIL = 'HOME_SCREEN_HOME_FAIL'

export const HOME_SCREEN_STORAGE_REQUEST = 'HOME_SCREEN_STORAGE_REQUEST'
export const HOME_SCREEN_STORAGE_SUCCESS = 'HOME_SCREEN_STORAGE_SUCCESS'
export const HOME_SCREEN_STORAGE_FAIL = 'SOME_SCREEN_STORAGE_FAIL'