export const GET_USER_PROFILE_DETAILS = 'GET_USER_PROFILE_DETAILS';
export const GET_USER_PROFILE_DETAILS_FAILED = 'GET_USER_PROFILE_DETAILS_FAILED';

export const UPDATE_USER_PROFILE_DETAILS = 'UPDATE_USER_PROFILE_DETAILS'
export const UPDATE_USER_PROFILE_DETAILS_FAILED = 'UPDATE_USER_PROFILE_DETAILS_FAILED'

export const EDIT_USER_NAME = 'EDIT_USER_NAME';
export const EDIT_USER_NAME_FAILED = 'EDIT_USER_NAME_FAILED';

export const EDIT_PHONE_NUMBER = 'EDIT_PHONE_NUMBER';
export const EDIT_PHONE_NUMBER_FAILED = 'EDIT_PHONE_NUMBER_FAILED';

export const ADD_NEW_SHIPPING_ADDRESS = 'ADD_NEW_SHIPPING_ADDRESS';
export const ADD_NEW_SHIPPING_ADDRESS_FAILED = 'ADD_NEW_SHIPPING_ADDRESS_FAILED';

export const EDIT_SHIPPING_ADDRESS = 'EDIT_SHIPPING_ADDRESS';
export const EDIT_SHIPPING_ADDRESS_FAILED = 'EDIT_SHIPPING_ADDRESS_FAILED';
